spring:
  application:
    name: eureka

server:
  port: 8084

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8084/eureka/